import "@/app/globals.css";
import LogoutButton from "@/components/LogOutButton";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RoutesLayout({ children, params }) {
  const { user } = await params;
  console.log("user", user);
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col bg-green-900">
          {/* Sidebar is persistent and overlays content */}
          <Sidebar user={user} />

          <nav className=" bg-blue-200 pl-16 pr-4 flex flex-row items-center relative">
            <img className="w-16" src="/fieldmaven1.png" />
            <span className="text-2xl font-bold px-4">
              Hello, Fieldmaven user
            </span>
            <LogoutButton className="absolute right-4" />
          </nav>
          <div className="">{children}</div>
        </main>
      </body>
    </html>
  );
}
