import Sidebar from "@/components/Sidebar";
import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children, params }) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col">
          {/* Sidebar is persistent and overlays content */}
          <Sidebar params={params} />
          <div className="ml-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
