const agroZones = {
  "Western Himalayan Region": {
    states: ["Jammu and Kashmir", "Himachal Pradesh", "Uttarakhand"],
    rainfall_cm: [150],
    summer_temp_c: [5, 30],
    winter_temp_c: [0, -4],
    crops: ["Maize", "Wheat", "Potato", "Barley", "Apple", "Pear"],
  },
  "Eastern Himalayan Region": {
    states: [
      "Sikkim",
      "Darjeeling",
      "Arunachal Pradesh",
      "Assam hills",
      "Nagaland",
      "Meghalaya",
      "Manipur",
      "Mizoram",
      "Tripura",
    ],
    rainfall_cm: [200],
    summer_temp_c: [25, 33],
    winter_temp_c: [11, 24],
    crops: [
      "Rice",
      "Potato",
      "Maize",
      "Tea",
      "Orange",
      "Pineapple",
      "Lime",
      "Litchi",
    ],
  },
  "Lower Gangetic Plains Region": {
    states: ["West Bengal", "Eastern Bihar", "Assam valley"],
    rainfall_cm: [100, 200],
    summer_temp_c: [26, 41],
    winter_temp_c: [9, 24],
    crops: [
      "Rice",
      "Jute",
      "Maize",
      "Potato",
      "Pulses",
      "Banana",
      "Mango",
      "Citrus",
    ],
  },
  "Middle Gangetic Plains Region": {
    states: ["Eastern Uttar Pradesh", "Bihar"],
    rainfall_cm: [100, 200],
    summer_temp_c: [26, 41],
    winter_temp_c: [9, 24],
    crops: [
      "Rice",
      "Maize",
      "Millets",
      "Wheat",
      "Gram",
      "Barley",
      "Peas",
      "Mustard",
      "Potato",
    ],
  },
  "Upper Gangetic Plains Region": {
    states: ["Central and Western Uttar Pradesh"],
    rainfall_cm: [75, 150],
    summer_temp_c: [26, 41],
    winter_temp_c: [7, 23],
    crops: [
      "Wheat",
      "Rice",
      "Sugarcane",
      "Millets",
      "Maize",
      "Gram",
      "Barley",
      "Oilseeds",
      "Pulses",
      "Cotton",
    ],
  },
  "Trans-Gangetic Plains Region": {
    states: [
      "Punjab",
      "Haryana",
      "Delhi",
      "Chandigarh",
      "Ganganagar (Rajasthan)",
    ],
    rainfall_cm: [70, 125],
    summer_temp_c: [26, 42],
    winter_temp_c: [7, 22],
    crops: [
      "Wheat",
      "Sugarcane",
      "Cotton",
      "Rice",
      "Gram",
      "Maize",
      "Millets",
      "Pulses",
      "Oilseeds",
    ],
  },
  "Eastern Plateau and Hills Region": {
    states: [
      "Chotanagpur plateau",
      "Rajmahal Hills",
      "Chhattisgarh",
      "Dandakaranya",
    ],
    rainfall_cm: [80, 150],
    summer_temp_c: [26, 34],
    winter_temp_c: [10, 27],
    crops: ["Rice", "Millets", "Maize", "Oilseeds", "Ragi", "Gram", "Potato"],
  },
  "Central Plateau and Hills Region": {
    states: [
      "Bundelkhand",
      "Baghelkhand",
      "Bhander plateau",
      "Malwa plateau",
      "Vindhyachal",
    ],
    rainfall_cm: [50, 100],
    summer_temp_c: [26, 40],
    winter_temp_c: [7, 24],
    crops: ["Millets", "Gram", "Barley", "Wheat", "Cotton", "Sunflower"],
  },
  "Western Plateau and Hills Region": {
    states: ["Southern Malwa plateau", "Deccan plateau (Maharashtra)"],
    rainfall_cm: [25, 75],
    summer_temp_c: [24, 41],
    winter_temp_c: [6, 23],
    crops: [
      "Jowar",
      "Cotton",
      "Sugarcane",
      "Rice",
      "Bajra",
      "Wheat",
      "Gram",
      "Pulses",
      "Potato",
      "Groundnut",
      "Oilseeds",
      "Oranges",
      "Grapes",
      "Bananas",
    ],
  },
  "Southern Plateau and Hills Region": {
    states: [
      "Southern Maharashtra",
      "Karnataka",
      "Western Andhra Pradesh",
      "Northern Tamil Nadu",
    ],
    rainfall_cm: [50, 100],
    summer_temp_c: [26, 42],
    winter_temp_c: [13, 21],
    crops: ["Minor Millets", "Coffee", "Tea", "Cardamom", "Spices"],
  },
  "East Coast Plains and Hills Region": {
    states: ["Orissa", "Andhra Pradesh", "Tamil Nadu", "Pondicherry"],
    rainfall_cm: [75, 150],
    summer_temp_c: [26, 32],
    winter_temp_c: [20, 29],
    crops: [
      "Rice",
      "Jute",
      "Tobacco",
      "Sugarcane",
      "Maize",
      "Millets",
      "Groundnut",
      "Oilseeds",
    ],
  },
  "West Coast Plains and Ghat Region": {
    states: ["Tamil Nadu", "Kerala", "Goa", "Karnataka", "Maharashtra"],
    rainfall_cm: [200],
    summer_temp_c: [26, 32],
    winter_temp_c: [19, 28],
    crops: [
      "Rice",
      "Coconut",
      "Oilseeds",
      "Sugarcane",
      "Millets",
      "Pulses",
      "Cotton",
      "Plantation Crops",
      "Spices",
    ],
  },
  "Gujarat Plains and Hills Region": {
    states: ["Gujarat"],
    rainfall_cm: [50, 100],
    summer_temp_c: [26, 42],
    winter_temp_c: [13, 29],
    crops: [
      "Groundnut",
      "Cotton",
      "Rice",
      "Millets",
      "Oilseeds",
      "Wheat",
      "Tobacco",
    ],
  },
  "Western Dry Region": {
    states: ["Western Rajasthan"],
    rainfall_cm: [0, 25],
    summer_temp_c: [28, 45],
    winter_temp_c: [5, 22],
    crops: ["Bajra", "Jowar", "Moth", "Wheat", "Gram"],
  },
  "Island Region": {
    states: ["Andaman and Nicobar", "Lakshadweep"],
    rainfall_cm: [300],
    summer_temp_c: [30],
    winter_temp_c: [25],
    crops: [
      "Rice",
      "Maize",
      "Millets",
      "Pulses",
      "Areca Nut",
      "Turmeric",
      "Cassava",
      "Coconut",
    ],
  },
};

export default agroZones;
