import Sidebar from "@/components/Sidebar";
import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children, params }) {
  // Access the dynamic user parameter from params
  const { user } = params;

  return (
    <html lang="en">
      <body>
        <Sidebar params={params} />
        <main>{children}</main>
      </body>
    </html>
  );
}
